# Cloudbuild file to build and deploy the app to Compute Engine (a VM instance)
# git pull from /home/scastanedag/Golden-at-work-APP
# and restart nginx with sudo systemctl restart nginx

steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute",
        "ssh",
        "scastanedag@instance-2",
        "--command=cd /home/scastanedag/Golden-at-work-APP && git pull && sudo systemctl restart nginx && sudo systemctl restart gunicorn.socket",
      ]
