# Generated by Django 4.2.5 on 2023-10-10 05:27

from django.db import migrations


def forwards_func(apps, schema_editor):
    Major = apps.get_model("main", "Major")

    majors = [
        "Administración de Empresas",
        "Antropología",
        "Arquitectura",
        "Artes Plásticas",
        "Biología",
        "Ciencia Política",
        "Ciencias de la Computación",
        "Cine y Televisión",
        "Contaduría Pública",
        "Derecho",
        "Diseño Gráfico",
        "Diseño Industrial",
        "Economía",
        "Enfermería",
        "Español y Filología Clásica",
        "Estadística",
        "Estudios Literarios",
        "Farmacia",
        "Filología e Idiomas: Alemán",
        "Filología e Idiomas: Francés",
        "Filología e Idiomas: Inglés",
        "Filosofía",
        "Física",
        "Fonoaudiología",
        "Geografía",
        "Geología",
        "Historia",
        "Ingeniería Agrícola",
        "Ingeniería Agronómica",
        "Ingeniería Civil",
        "Ingeniería de Sistemas y Computación",
        "Ingeniería Eléctrica",
        "Ingeniería Electrónica",
        "Ingeniería Industrial",
        "Ingeniería Mecánica",
        "Ingeniería Mecatrónica",
        "Ingeniería Química",
        "Lingüística",
        "Matemáticas",
        "Medicina",
        "Medicina Veterinaria",
        "Música",
        "Música Instrumental",
        "Nutrición y Dietética",
        "Odontología",
        "Psicología",
        "Química",
        "Sociología",
        "Terapia Ocupacional",
        "Trabajo Social"
    ]

    for major in majors:
        Major.objects.create(name=major)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
