# Generated by Django 4.2.5 on 2023-10-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_implement_borrow_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='return_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='borrow_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_label',
            field=models.CharField(choices=[('DAMAGED', 'Dañado'), ('LOST', 'Perdido'), ('WORKING', 'Funcionando'), ('ACCEPTABLE', 'Prestable')], default='WORKING', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Reservado'), ('BORROWED', 'Prestado'), ('RETURNED', 'Devuelto')], default='AVAILABLE', max_length=20),
        ),
    ]
