# Generated by Django 4.2.5 on 2023-10-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_return_date_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implement',
            name='available',
        ),
        migrations.AddField(
            model_name='implement',
            name='image',
            field=models.ImageField(blank=True, upload_to='implements/'),
        ),
    ]
