# Generated by Django 4.1.7 on 2023-10-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_implement_available_implement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancel_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
