# Generated by Django 4.1.7 on 2023-11-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_loginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='implement',
            name='multipleCarnets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='implement',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Pequeño'), ('MEDIUM', 'Mediano'), ('BIG', 'Grande')], default='Pequeño', max_length=10),
        ),
    ]
