
const entraslation={
    "Añadir implemento": "Add Implement",
    "Nombre": "Name",
    "Descripcion": "Description",
    "Subir imagen": "Upload Image",
    "Por favor ingrese el nombre del implemento": "Please enter the name of the implement",
    "Por favor ingrese una descripción del implemento": "Please enter a description of the implement",
    "Por favor ingrese una imagen del implemento": "Please enter an image of the implement",
    "Historial": "History",
    "Eliminar implemento": "Delete Implement",
    "ID": "ID",
    "Implemento": "Implement",
    "Día": "Day",
    "Hora de inicio": "Start Time",
    "Hora de fin": "End Time",
    "Usuario": "User",
    "Acciones": "Actions",
    "Prestar": "Lend",
    "Devolver": "Return",
    "Devuelto": "Returned",
    "Configuración de sesión": "Session Settings",
    "Eliminar cuenta": "Delete Account",
    "Mi cuenta": "My Account",
    "Cerrar sesión": "Log Out",
    "Buscar...": "Search...",
    "Disponible": "Available",
    "Varios Carnets": "Multiple Cards",
    "Pequeño": "Small",
    "Mediano": "Medium",
    "Grande": "Large",
    "Login": "Login",
    "Email": "Email",
    "Contraseña": "Password",
    "¿Olvidaste tú contraseña?": "Forgot Your Password?",
    "Ingresar": "Enter",
    "¿No tienes una cuenta? Regístrate": "Don't have an account? Sign Up",
    "Exportar a Excel": "Export to Excel",
    "Registro": "Registration",
    "Apellido": "Last Name",
    "Confirmar contraseña": "Confirm Password",
    "Documento": "Document",
    "Por favor seleccione un programa académico": "Please select an academic program",
    "Por favor ingrese su nombre": "Please enter your first name",
    "Por favor ingrese su apellido": "Please enter your last name",
    "Por favor ingrese su documento": "Please enter your document",
    "Por favor ingrese su correo electrónico": "Please enter your email",
    "Las contraseñas no coinciden.": "Passwords do not match.",
    "Por favor ingrese un correo electrónico de la UNAL": "Please enter a UNAL email address",
    "Debe autorizar el uso y la recopilación de datos para continuar.": "You must authorize the use and collection of data to continue.",
    "Registrarse": "Register",
    "Al crear su cuenta, autoriza el uso y la recopilación de sus datos personales para esta aplicación.": "By creating your account, you authorize the use and collection of your personal data for this application.",
    "Recuperar contraseña": "Reset Password",
    "Ingrese su correo electrónico para recuperar su contraseña": "Enter your email to reset your password",
    "Nueva contraseña": "New Password",
    "Enviar": "Send",
    "Inglés": "English",
    "Francés": "French",
    "Español": "Spanish",
    "Portugués": "Portuguese",
    "Idioma": "Language"
};
export default entraslation