const estraslation={
    "Añadir implemento": "Añadir implemento",
    "Nombre": "Nombre",
    "Descripcion": "Descripcion",
    "Subir imagen": "Subir imagen",
    "Por favor ingrese el nombre del implemento": "Por favor ingrese el nombre del implemento",
    "Por favor ingrese una descripción del implemento": "Por favor ingrese una descripción del implemento",
    "Por favor ingrese una imagen del implemento": "Por favor ingrese una imagen del implemento",
    "Historial": "Historial",
    "Eliminar implemento": "Eliminar implemento",
    "ID": "ID",
    "Implemento": "Implemento",
    "Día": "Día",
    "Hora de inicio": "Hora de inicio",
    "Hora de fin": "Hora de fin",
    "Usuario": "Usuario",
    "Acciones": "Acciones",
    "Prestar": "Prestar",
    "Devolver": "Devolver",
    "Devuelto": "Devuelto",
    "Configuración de sesión": "Configuración de sesión",
    "Eliminar cuenta": "Eliminar cuenta",
    "Mi cuenta": "Mi cuenta",
    "Cerrar sesión": "Cerrar sesión",
    "Buscar...": "Buscar...",
    "Disponible": "Disponible",
    "Varios Carnets": "Varios Carnets",
    "Pequeño": "Pequeño",
    "Mediano": "Mediano",
    "Grande": "Grande",
    "Login": "Login",
    "Email": "Correo Electrónico",
    "Contraseña": "Contraseña",
    "¿Olvidaste tú contraseña?": "¿Olvidaste tú contraseña?",
    "Ingresar": "Ingresar",
    "¿No tienes una cuenta? Regístrate": "¿No tienes una cuenta? Regístrate",
    "Exportar a Excel": "Exportar a Excel",
    "Registro": "Registro",
    "Apellido": "Apellido",
    "Confirmar contraseña": "Confirmar contraseña",
    "Documento": "Documento",
    "Por favor seleccione un programa académico": "Por favor seleccione un programa académico",
    "Por favor ingrese su nombre": "Por favor ingrese su nombre",
    "Por favor ingrese su apellido": "Por favor ingrese su apellido",
    "Por favor ingrese su documento": "Por favor ingrese su documento",
    "Por favor ingrese su correo electrónico": "Por favor ingrese su correo electrónico",
    "Las contraseñas no coinciden.": "Las contraseñas no coinciden.",
    "Por favor ingrese un correo electrónico de la UNAL": "Por favor ingrese un correo electrónico de la UNAL",
    "Debe autorizar el uso y la recopilación de datos para continuar.": "Debe autorizar el uso y la recopilación de datos para continuar.",
    "Registrarse": "Registrarse",
    "Al crear su cuenta, autoriza el uso y la recopilación de sus datos personales para esta aplicación.": "Al crear su cuenta, autoriza el uso y la recopilación de sus datos personales para esta aplicación.",
    "Recuperar contraseña": "Recuperar contraseña",
    "Ingrese su correo electrónico para recuperar su contraseña": "Ingrese su correo electrónico para recuperar su contraseña",
    "Nueva contraseña": "Nueva contraseña",
    "Enviar": "Enviar"
};
export default estraslation