const frtraslation={
    "Añadir implemento": "Ajouter un outil",
          "Nombre": "Nom",
          "Descripcion": "Description",
          "Subir imagen": "Télécharger l'image",
          "Por favor ingrese el nombre del implemento": "Veuillez entrer le nom de l'outil",
          "Por favor ingrese una descripción del implemento": "Veuillez entrer une description de l'outil",
          "Por favor ingrese una imagen del implemento": "Veuillez insérer une image de l'outil",
          "Historial": "Historique",
          "Eliminar implemento": "Supprimer l'outil",
          "ID": "ID",
          "Implemento": "Outil",
          "Día": "Jour",
          "Hora de inicio": "Heure de début",
          "Hora de fin": "Heure de fin",
          "Usuario": "Utilisateur",
          "Acciones": "Actions",
          "Prestar": "Prêter",
          "Devolver": "Retourner",
          "Devuelto": "Retourné",
          "Configuración de sesión": "Paramètres de Session",
          "Eliminar cuenta": "Supprimer le Compte",
          "Mi cuenta": "Mon Compte",
          "Cerrar sesión": "Se Déconnecter",
          "Buscar...": "Rechercher...",
          "Disponible": "Disponible",
          "Varios Carnets": "Plusieurs Cartes",
          "Pequeño": "Petit",
          "Mediano": "Moyen",
          "Grande": "Grand",
          "Login": "Connexion",
          "Email": "E-mail",
          "Contraseña": "Mot de passe",
          "¿Olvidaste tú contraseña?": "Mot de passe oublié?",
          "Ingresar": "Entrer",
          "¿No tienes una cuenta? Regístrate": "Pas de compte? Inscrivez-vous",
        "Exportar a Excel": "Exporter vers Excel",
        "Registro": "Inscription",
        "Apellido": "Nom de famille",
        "Confirmar contraseña": "Confirmer le mot de passe",
        "Documento": "Document",
        "Por favor seleccione un programa académico": "Veuillez sélectionner un programme académique",
        "Por favor ingrese su nombre": "Veuillez saisir votre prénom",
        "Por favor ingrese su apellido": "Veuillez saisir votre nom de famille",
        "Por favor ingrese su documento": "Veuillez saisir votre document",
        "Por favor ingrese su correo electrónico": "Veuillez saisir votre e-mail",
        "Las contraseñas no coinciden.": "Les mots de passe ne correspondent pas.",
        "Por favor ingrese un correo electrónico de la UNAL": "Veuillez saisir une adresse e-mail de l'UNAL",
        "Debe autorizar el uso y la recopilación de datos para continuar.": "Vous devez autoriser l'utilisation et la collecte de données pour continuer.",
        "Registrarse": "S'inscrire",
        "Al crear su cuenta, autoriza el uso y la recopilación de sus datos personales para esta aplicación.": "En créant votre compte, vous autorisez l'utilisation et la collecte de vos données personnelles pour cette application.",
        "Recuperar contraseña": "Réinitialiser le mot de passe",
        "Ingrese su correo electrónico para recuperar su contraseña": "Entrez votre e-mail pour réinitialiser votre mot de passe",
        "Nueva contraseña": "Nouveau mot de passe",
        "Enviar": "Envoyer"
};
export default frtraslation