const pttraslation={
    "Añadir implemento": "Adicionar Implemento",
    "Nombre": "Nome",
    "Descripcion": "Descrição",
    "Subir imagen": "Carregar Imagem",
    "Por favor ingrese el nombre del implemento": "Por favor, insira o nome do implemento",
    "Por favor ingrese una descripción del implemento": "Por favor, insira uma descrição do implemento",
    "Por favor ingrese una imagen del implemento": "Por favor, insira uma imagem do implemento",
    "Historial": "Histórico",
    "Eliminar implemento": "Eliminar Implemento",
    "ID": "ID",
    "Implemento": "Implemento",
    "Día": "Dia",
    "Hora de inicio": "Hora de Início",
    "Hora de fin": "Hora de Término",
    "Usuario": "Usuário",
    "Acciones": "Ações",
    "Prestar": "Emprestar",
    "Devolver": "Devolver",
    "Devuelto": "Devolvido",
    "Configuración de sesión": "Configurações de Sessão",
    "Eliminar cuenta": "Excluir Conta",
    "Mi cuenta": "Minha Conta",
    "Cerrar sesión": "Sair",
    "Buscar...": "Procurar...",
    "Disponible": "Disponível",
    "Varios Carnets": "Múltiplos Cartões",
    "Pequeño": "Pequeno",
    "Mediano": "Médio",
    "Grande": "Grande",
    "Login": "Login",
    "Email": "Email",
    "Contraseña": "Senha",
    "¿Olvidaste tú contraseña?": "Esqueceu Sua Senha?",
    "Ingresar": "Entrar",
    "¿No tienes una cuenta? Regístrate": "Não tem uma conta? Cadastre-se",
    "Exportar a Excel": "Exportar para Excel",
    "Registro": "Registro",
    "Apellido": "Sobrenome",
    "Confirmar contraseña": "Confirmar Senha",
    "Documento": "Documento",
    "Por favor seleccione un programa académico": "Por favor, selecione um programa acadêmico",
    "Por favor ingrese su nombre": "Por favor, insira seu nome",
    "Por favor ingrese su apellido": "Por favor, insira seu sobrenome",
    "Por favor ingrese su documento": "Por favor, insira seu documento",
    "Por favor ingrese su correo electrónico": "Por favor, insira seu e-mail",
    "Las contraseñas no coinciden.": "As senhas não coincidem.",
    "Por favor ingrese un correo electrónico de la UNAL": "Por favor, insira um e-mail da UNAL",
    "Debe autorizar el uso y la recopilación de datos para continuar.": "Você deve autorizar o uso e a coleta de dados para continuar.",
    "Registrarse": "Registrar-se",
    "Al crear su cuenta, autoriza el uso y la recopilación de sus datos personales para esta aplicación.": "Ao criar sua conta, você autoriza o uso e a coleta de seus dados pessoais para esta aplicação.",
    "Recuperar contraseña": "Recuperar Senha",
    "Ingrese su correo electrónico para recuperar su contraseña": "Digite seu e-mail para recuperar sua senha",
    "Nueva contraseña": "Nova Senha",
    "Enviar": "Enviar",
    "Inglés": "Inglês",
    "Francés": "Francês",
    "Español": "Espanhol",
    "Portugués": "Português",
    "Idioma": "Língua"
};
export default pttraslation