# Generated by Django 4.2.5 on 2023-10-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_auth', '0002_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
