# Generated by Django 4.2.5 on 2023-10-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_auth', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
