# Generated by Django 4.2.5 on 2023-10-10 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231010_0527'),
        ('back_auth', '0004_user_recovery_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='career',
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.major'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Implement',
        ),
    ]
