# Generated by Django 4.2.5 on 2023-10-11 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231010_0527'),
        ('back_auth', '0005_remove_user_career_user_major_delete_implement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.major'),
        ),
    ]
