# Generated by Django 4.2.5 on 2023-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_auth', '0006_alter_user_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='damaged_returns_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lost_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
