# Generated by Django 4.2.7 on 2023-11-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_loginfo'),
        ('back_auth', '0007_user_damaged_returns_count_user_lost_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorits',
            field=models.ManyToManyField(to='main.implement'),
        ),
    ]
